/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_isac_jni_ExampleParametersJNI */

#ifndef _Included_com_isac_jni_ExampleParametersJNI
#define _Included_com_isac_jni_ExampleParametersJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_isac_jni_ExampleParametersJNI
 * Method:    sumIntegers
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_com_isac_jni_ExampleParametersJNI_sumIntegers
  (JNIEnv*, jobject, jint, jint);

/*
 * Class:     com_isac_jni_ExampleParametersJNI
 * Method:    sayHelloToMe
 * Signature: (Ljava/lang/String;Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_isac_jni_ExampleParametersJNI_sayHelloToMe
  (JNIEnv*, jobject, jstring, jboolean);

#ifdef __cplusplus
}
#endif
#endif
